source 'https://rubygems.org'

gem 'sinatroid', path: 'sinatroid'

group :development do
	gem 'pry' # cl
	gem 'shotgun' # for backend development
	gem 'thin' # for frontend developement (doesn't reload changed ruby code)
end

